In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [9]:
name = []
rating = []
job_description = []
total_employees = []
age = []
location = []

In [22]:
for j in range(1, 10):
    url = 'https://www.ambitionbox.com/list-of-companies?sortBy=rating&page={}'.format(j)
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1"
    }

    webpage1 = requests.get(url, headers=headers)
    soup1 = BeautifulSoup(webpage1.content, 'html.parser')

    company1 = soup1.find_all('div', class_='companyCardWrapper__metaInformation')

    for i in company1:
        interlinking_span = i.find('span', class_='companyCardWrapper__interLinking')
        if interlinking_span:
            a = interlinking_span.text.strip().split('|')
            if len(a) == 4:
                job_description.append(a[0])
                total_employees.append(a[1])
                age.append(a[2])
                location.append(a[3])
                name.append(i.find('h2', class_="companyCardWrapper__companyName").text.strip())
            else:
                job_description.append(None)
                total_employees.append(None)
                age.append(None)
                location.append(None)
                name.append(i.find('h2', class_="companyCardWrapper__companyName").text.strip())
        else:
            job_description.append(None)
            total_employees.append(None)
            age.append(None)
            location.append(None)
            name.append(i.find('h2', class_="companyCardWrapper__companyName").text.strip())
        
        rating_span = i.find('span', class_='companyCardWrapper__companyRatingValue')
        if rating_span:
            rating.append(rating_span.text.strip())
        else:
            rating.append(None)
        
        b = i.find_all('span', class_='companyCardWrapper__ratingValues')
        if len(b) == 1:
            positive.append(b[0].text.strip())

        elif len(b) == 2:
            positive.append(b[0].text.strip())

        else:
            positive.append(None)


# Ensure all lists are of the same length
max_length = max(len(name), len(rating), len(job_description), len(total_employees), len(age), len(location), len(positive), len(negative))

def pad_list(lst, length):
    return lst + [None] * (length - len(lst))

name = pad_list(name, max_length)
rating = pad_list(rating, max_length)
job_description = pad_list(job_description, max_length)
total_employees = pad_list(total_employees, max_length)
age = pad_list(age, max_length)
location = pad_list(location, max_length)
positive = pad_list(positive, max_length)
negative = pad_list(negative, max_length)

# Create DataFrame
data = {
    'Name': name,
    'Rating': rating,
    'Job Description': job_description,
    'Total Employees': total_employees,
    'Age': age,
    'Location': location,
    'Positive': positive,

}

final = pd.DataFrame(data)

In [27]:
final

,Name,Rating,Job Description,Total Employees,Age,Location,Positive
0,Lavender Technology,5.0,IT Services & Consulting,5k-10k Employees,14 years old,USA +4 more,"Company Culture, Promotions / Appraisal, Skill..."
1,None,5.0,None,None,None,None,"Company Culture, Work Life Balance, Work Satis..."
2,None,5.0,None,None,None,None,"Company Culture, Work Life Balance, Work Satis..."
3,Jayasree Techno Solutions,5.0,Chemicals,11-50 Employees,8 years old,Hyderabad/Secunderabad +11 more,"Company Culture, Work Life Balance, Work Satis..."
4,None,5.0,None,None,None,None,"Work Satisfaction, Job Security, Skill Develop..."
...,...,...,...,...,...,...,...
635,Edooni Solutions,5.0,IT Services & Consulting,51-200 Employees (Global),14 years old,Delhi,"Work Life Balance, Work Satisfaction, Salary &..."
636,Big Cinemas,5.0,None,None,None,None,"Skill Development / Learning, Promotions / App..."
637,Ganesh Housing Corporation,5.0,None,None,None,None,"Promotions / Appraisal, Work Life Balance, Job..."
638,Sabero Organics Gujarat,5.0,Chemicals,Public,33 years old,Sarigam +2 more,"Company Culture, Work Life Balance, Work Satis..."
639,Glansa Solutions,5.0,Financial Services,51-200 Employees,24 years old,Secunderabad,"Work Life Balance, Company Culture, Job Security"

In [24]:
final.to_csv('final_company.csv')

In [25]:
final.drop_duplicates('Name')

,Name,Rating,Job Description,Total Employees,Age,Location,Positive
0,Lavender Technology,5.0,IT Services & Consulting,5k-10k Employees,14 years old,USA +4 more,"Company Culture, Promotions / Appraisal, Skill..."
1,None,5.0,None,None,None,None,"Company Culture, Work Life Balance, Work Satis..."
3,Jayasree Techno Solutions,5.0,Chemicals,11-50 Employees,8 years old,Hyderabad/Secunderabad +11 more,"Company Culture, Work Life Balance, Work Satis..."
6,YUHIRO Technologies,5.0,IT Services & Consulting,11-50 Employees,12 years old,Kochi +10 more,"Work Life Balance, Promotions / Appraisal, Sal..."
8,Futurewins Trading Solutions,5.0,Management Consulting,51-200 Employees (Global),14 years old,Ernakulam +4 more,"Company Culture, Work Life Balance, Work Satis..."
...,...,...,...,...,...,...,...
474,Coffee Day Hotels Resorts,5.0,None,None,None,None,"Company Culture, Work Life Balance, Skill Deve..."
476,Big Cinemas,5.0,None,None,None,None,"Skill Development / Learning, Promotions / App..."
477,Ganesh Housing Corporation,5.0,None,None,None,None,"Promotions / Appraisal, Work Life Balance, Job..."
540,Dovekie Technologies,5.0,None,None,None,None,"Company Culture, Work Life Balance, Work Satis..."
618,Duniya Hotel,5.0,None,None,None,None,"Company Culture, Work Life Balance, Work Satis..."

In [20]:
len(final.drop_duplicates('Name'))

154

In [26]:
print(len(name), len(rating), len(job_description), len(total_employees), len(age), len(location), len(positive), len(negative))

640 640 640 640 640 640 640 640